version: 0.2
# AWS CodeBuild spec.
# See : https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
env:
  variables:
    SLS_DEBUG: "*"
phases:
  install:
    on-failure: ABORT
    commands:
      - cd shell-ms
      - nodejs --version
      - npm --version
      - npm install
      - npm install -g serverless
      - npx serverless dynamodb install
  pre_build:
    on-failure: ABORT
    commands:
      - pwd
      - cd shell-ms
      - npm run test
      - exit $?
  build:
    on-failure: ABORT
    commands:
      - pwd
      - cd shell-ms
      - sls deploy --stage production --verbose --conceal
      - exit $?

