/*
 *
 * MIT License.
 *
 */
export enum NotificationKey {
  AUTH0_ERROR_DESCRIPTION = 'AUTH0_ERROR_DESCRIPTION',
  NO_CODE_JWT_CODE = 'NO_CODE_JWT_CODE',
  TOKEN_EXHCHANGE_FAILURE_ERROR = 'TOKEN_EXHCHANGE_FAILURE_ERROR',
  TOKEN_EXCHANGE_FAILURE = 'TOKEN_EXCHANGE_FAILURE',
  USERS_CREATE_FAIL = 'USERS_CREATE_FAIL',
  USERS_UPDATE_FAIL = 'USERS_UPDATE_FAIL',
  USERS_FETCH_FAIL = 'USERS_FETCH_FAIL',
  USERS_EMAIL_UPDATED = 'USERS_EMAIL_UPDATED',
  USER_ROLES_FETCH_FAIL = 'USER_ROLES_FETCH_FAIL',
  USERS_INVITATION_SENT = 'USERS_INVITATION_SENT',
  USER_PROFILE_FETCH_FAIL = 'USER_PROFILE_FETCH_FAIL',
}
