/*
 *
 * MIT License.
 *
 */

import { DisciplineType, EventTypes } from '../model/types';

export const YEARS = Array.from({ length: new Date().getFullYear() - 2023 + 1 }, (_, i) => {
  const year: number = 2023 + i;
  return { key: year, value: year, text: year };
});

export const GENDERS = [
  { key: 'male', value: 'male', text: 'Male' },
  { key: 'female', value: 'female', text: 'Female' },
];

export const DISCIPLINES: {
  key: DisciplineType;
  value: DisciplineType;
  text: DisciplineType;
}[] = [
  { key: 'Road', value: 'Road', text: 'Road' },
  { key: 'MTB', value: 'MTB', text: 'MTB' },
  { key: 'BMX', value: 'BMX', text: 'BMX' },
  { key: 'CX', value: 'CX', text: 'CX' },
  { key: 'DH', value: 'DH', text: 'DH' },
  { key: 'Enduro', value: 'Enduro', text: 'Enduro' },
  { key: 'Track', value: 'Track', text: 'Track' },
  { key: 'E-Racing', value: 'E-Racing', text: 'E-Racing' },
  { key: 'Gravel', value: 'Gravel', text: 'Gravel' },
];

export const EVENT_TYPES: EventTypes = {
  MTB: [
    { key: 'XCO', value: 'XCO', text: 'XCO' },
    { key: 'XCC', value: 'XCC', text: 'XCC' },
    { key: 'XCM', value: 'XCM', text: 'XCM' },
    { key: 'XCR', value: 'XCR', text: 'XCR' },
  ],
  Road: [
    { key: '1 day', value: '1 day', text: '1 day' },
    { key: 'Criterium', value: 'Criterium', text: 'Criterium' },
    { key: 'Time-trial', value: 'Time-trial', text: 'Time-trial' },
    { key: 'Team-time-trial', value: 'Team-time-trial', text: 'Team-time-trial' },
    { key: 'Stage', value: 'Stage', text: 'Stage' },
  ],
  CX: [{ key: 'CX', value: 'CX', text: 'CX' }],
  DH: [{ key: 'DH', value: 'DH', text: 'DH' }],
  Enduro: [{ key: 'Enduro', value: 'Enduro', text: 'Enduro' }],
  BMX: [{ key: 'BMX', value: 'BMX', text: 'BMX' }],
  Track: [
    { key: 'Individual Pursuit', value: 'Individual Pursuit', text: 'Individual Pursuit' },
    { key: 'Team Pursuit', value: 'Team Pursuit', text: 'Team Pursuit' },
    { key: 'Point Score', value: 'Point Score', text: 'Point Score' },
    { key: 'Scratch', value: 'Scratch', text: 'Scratch' },
    { key: 'Omnium', value: 'Omnium', text: 'Omnium' },
    { key: 'Madison', value: 'Madison', text: 'Madison' },
    { key: 'Sprint', value: 'Sprint', text: 'Sprint' },
    { key: 'Team Sprint', value: 'Team Sprint', text: 'Team Sprint' },
    { key: 'Time Trial', value: 'Time Trial', text: 'Time Trial' },
    { key: 'Keirin', value: 'Keirin', text: 'Keirin' },
  ],
  'E-Racing': [{ key: 'E-Racing', value: 'E-Racing', text: 'E-Racing' }],
  Gravel: [{ key: 'Gravel', value: 'Gravel', text: 'Gravel' }],
};

export const COURSE_PROFILES: EventTypes = {
  MTB: [
    { key: 'Mud', value: 'Mud', text: 'Mud' },
    { key: 'Sand', value: 'Sand', text: 'Sand' },
    { key: 'Dry', value: 'Dry', text: 'Dry' },
    { key: 'Mix', value: 'Mix', text: 'Mix' },
  ],
  Road: [
    { key: 'Flat', value: 'Flat', text: 'Flat' },
    { key: 'Rolling hills', value: 'Rolling hills', text: 'Rolling hills' },
    { key: 'Hills', value: 'Hills', text: 'Hills' },
    { key: 'Mountains', value: 'Mountains', text: 'Mountains' },
    { key: 'High mountains', value: 'High mountains', text: 'High mountains' },
  ],
  CX: [
    { key: 'Mud', value: 'Mud', text: 'Mud' },
    { key: 'Sand', value: 'Sand', text: 'Sand' },
    { key: 'Dry', value: 'Dry', text: 'Dry' },
    { key: 'Mix', value: 'Mix', text: 'Mix' },
  ],
  DH: [
    { key: 'Mud', value: 'Mud', text: 'Mud' },
    { key: 'Dry', value: 'Dry', text: 'Dry' },
    { key: 'Mix', value: 'Mix', text: 'Mix' },
  ],
  Enduro: [
    { key: 'Mud', value: 'Mud', text: 'Mud' },
    { key: 'Dry', value: 'Dry', text: 'Dry' },
    { key: 'Mix', value: 'Mix', text: 'Mix' },
  ],
  BMX: [
    { key: 'Super-X', value: 'Super-X', text: 'Super-X' },
    { key: 'Standard', value: 'Standard', text: 'Standard' },
  ],
  Track: [
    { key: 'Indoor', value: 'Indoor', text: 'Indoor' },
    { key: 'Outdoor', value: 'Outdoor', text: 'Outdoor' },
  ],
  'E-Racing': [{ key: 'E-Racing', value: 'E-Racing', text: 'E-Racing' }],
  Gravel: [{ key: 'Gravel', value: 'Gravel', text: 'Gravel' }],
};

export const CATEGORIES = [
  { key: 'U17', value: 'U17', text: 'U17' },
  { key: 'U19', value: 'U19', text: 'U19' },
  { key: 'U23', value: 'U23', text: 'U23' },
  { key: 'Elite', value: 'Elite', text: 'Elite' },
];

export const CLASSES = [
  { key: 'National', value: 'National', text: 'National' },
  { key: 'National:Championship', value: 'National:Championship', text: 'National Championship' },
  { key: 'International:Regional', value: 'International:Regional', text: 'International: Regional' },
  { key: 'International:National', value: 'International:National', text: 'International: National' },
  { key: 'UCI:Cat1', value: 'UCI:Cat1', text: 'UCI: Cat 1' },
  { key: 'UCI:Cat2', value: 'UCI:Cat2', text: 'UCI: Cat 2' },
  { key: 'UCI:WorldCup', value: 'UCI:WorldCup', text: 'UCI: World Cup' },
  { key: 'UCI:EuropeanChampionship', value: 'UCI:EuropeanChampionship', text: 'UCI: European Championship' },
  { key: 'UCI:WorldChampionship', value: 'UCI:WorldChampionship', text: 'UCI: World Championship' },
];

export const COUNTRIES_MOST_COMMON = [
  { key: 'fi', text: 'Finland', flag: 'fi', value: 'fi' },
  { key: 'ee', text: 'Estonia', flag: 'ee', value: 'ee' },
  { key: 'se', text: 'Sweden', flag: 'se', value: 'se' },
];

export const COUNTRIES_COMMON = [
  { key: 'be', text: 'Belgium', flag: 'be', value: 'be' },
  { key: 'fr', text: 'France', flag: 'fr', value: 'fr' },
  { key: 'de', text: 'Germany', flag: 'de', value: 'de' },
  { key: 'it', text: 'Italy', flag: 'it', value: 'it' },
  { key: 'nl', text: 'Netherlands', flag: 'nl', value: 'nl' },
  { key: 'es', text: 'Spain', flag: 'es', value: 'es' },
  { key: 'ch', text: 'Switzerland', flag: 'ch', value: 'ch' },
];

export const COUNTRIES_NO_COMMON = [
  { key: 'af', text: 'Afghanistan', flag: 'af', value: 'af' },
  { key: 'ax', text: 'Aland Islands', flag: 'ax', value: 'ax' },
  { key: 'al', text: 'Albania', flag: 'al', value: 'al' },
  { key: 'dz', text: 'Algeria', flag: 'dz', value: 'dz' },
  { key: 'as', text: 'American Samoa', flag: 'as', value: 'as' },
  { key: 'ad', text: 'Andorra', flag: 'ad', value: 'ad' },
  { key: 'ao', text: 'Angola', flag: 'ao', value: 'ao' },
  { key: 'ai', text: 'Anguilla', flag: 'ai', value: 'ai' },
  { key: 'ag', text: 'Antigua', flag: 'ag', value: 'ag' },
  { key: 'ar', text: 'Argentina', flag: 'ar', value: 'ar' },
  { key: 'am', text: 'Armenia', flag: 'am', value: 'am' },
  { key: 'aw', text: 'Aruba', flag: 'aw', value: 'aw' },
  { key: 'au', text: 'Australia', flag: 'au', value: 'au' },
  { key: 'at', text: 'Austria', flag: 'at', value: 'at' },
  { key: 'az', text: 'Azerbaijan', flag: 'az', value: 'az' },
  { key: 'bs', text: 'Bahamas', flag: 'bs', value: 'bs' },
  { key: 'bh', text: 'Bahrain', flag: 'bh', value: 'bh' },
  { key: 'bd', text: 'Bangladesh', flag: 'bd', value: 'bd' },
  { key: 'bb', text: 'Barbados', flag: 'bb', value: 'bb' },
  { key: 'by', text: 'Belarus', flag: 'by', value: 'by' },
  { key: 'bz', text: 'Belize', flag: 'bz', value: 'bz' },
  { key: 'bj', text: 'Benin', flag: 'bj', value: 'bj' },
  { key: 'bm', text: 'Bermuda', flag: 'bm', value: 'bm' },
  { key: 'bt', text: 'Bhutan', flag: 'bt', value: 'bt' },
  { key: 'bo', text: 'Bolivia', flag: 'bo', value: 'bo' },
  { key: 'ba', text: 'Bosnia', flag: 'ba', value: 'ba' },
  { key: 'bw', text: 'Botswana', flag: 'bw', value: 'bw' },
  { key: 'bv', text: 'Bouvet Island', flag: 'bv', value: 'bv' },
  { key: 'br', text: 'Brazil', flag: 'br', value: 'br' },
  { key: 'vg', text: 'British Virgin Islands', flag: 'vg', value: 'vg' },
  { key: 'bn', text: 'Brunei', flag: 'bn', value: 'bn' },
  { key: 'bg', text: 'Bulgaria', flag: 'bg', value: 'bg' },
  { key: 'bf', text: 'Burkina Faso', flag: 'bf', value: 'bf' },
  { key: 'mm', text: 'Myanmar/Burma', flag: 'mm', value: 'mm' },
  { key: 'bi', text: 'Burundi', flag: 'bi', value: 'bi' },
  { key: 'tc', text: 'Caicos Islands', flag: 'tc', value: 'tc' },
  { key: 'kh', text: 'Cambodia', flag: 'kh', value: 'kh' },
  { key: 'cm', text: 'Cameroon', flag: 'cm', value: 'cm' },
  { key: 'ca', text: 'Canada', flag: 'ca', value: 'ca' },
  { key: 'cv', text: 'Cape Verde', flag: 'cv', value: 'cv' },
  { key: 'ky', text: 'Cayman Islands', flag: 'ky', value: 'ky' },
  { key: 'cf', text: 'Central African Republic', flag: 'cf', value: 'cf' },
  { key: 'td', text: 'Chad', flag: 'td', value: 'td' },
  { key: 'cl', text: 'Chile', flag: 'cl', value: 'cl' },
  { key: 'cn', text: 'China', flag: 'cn', value: 'cn' },
  { key: 'cx', text: 'Christmas Island', flag: 'cx', value: 'cx' },
  { key: 'cc', text: 'Cocos Islands', flag: 'cc', value: 'cc' },
  { key: 'co', text: 'Colombia', flag: 'co', value: 'co' },
  { key: 'km', text: 'Comoros', flag: 'km', value: 'km' },
  { key: 'cd', text: 'Congo', flag: 'cd', value: 'cd' },
  { key: 'cg', text: 'Congo Brazzaville', flag: 'cg', value: 'cg' },
  { key: 'ck', text: 'Cook Islands', flag: 'ck', value: 'ck' },
  { key: 'cr', text: 'Costa Rica', flag: 'cr', value: 'cr' },
  { key: 'ci', text: 'Cote Divoire', flag: 'ci', value: 'ci' },
  { key: 'hr', text: 'Croatia', flag: 'hr', value: 'hr' },
  { key: 'cu', text: 'Cuba', flag: 'cu', value: 'cu' },
  { key: 'cy', text: 'Cyprus', flag: 'cy', value: 'cy' },
  { key: 'cz', text: 'Czech Republic', flag: 'cz', value: 'cz' },
  { key: 'dk', text: 'Denmark', flag: 'dk', value: 'dk' },
  { key: 'dj', text: 'Djibouti', flag: 'dj', value: 'dj' },
  { key: 'dm', text: 'Dominica', flag: 'dm', value: 'dm' },
  { key: 'do', text: 'Dominican Republic', flag: 'do', value: 'do' },
  { key: 'ec', text: 'Ecuador', flag: 'ec', value: 'ec' },
  { key: 'eg', text: 'Egypt', flag: 'eg', value: 'eg' },
  { key: 'sv', text: 'El Salvador', flag: 'sv', value: 'sv' },
  { key: 'gq', text: 'Equatorial Guinea', flag: 'gq', value: 'gq' },
  { key: 'er', text: 'Eritrea', flag: 'er', value: 'er' },
  { key: 'et', text: 'Ethiopia', flag: 'et', value: 'et' },
  { key: 'eu', text: 'Europeanunion', flag: 'eu', value: 'eu' },
  { key: 'fk', text: 'Falkland Islands', flag: 'fk', value: 'fk' },
  { key: 'fo', text: 'Faroe Islands', flag: 'fo', value: 'fo' },
  { key: 'fj', text: 'Fiji', flag: 'fj', value: 'fj' },
  { key: 'gf', text: 'French Guiana', flag: 'gf', value: 'gf' },
  { key: 'pf', text: 'French Polynesia', flag: 'pf', value: 'pf' },
  { key: 'tf', text: 'French Territories', flag: 'tf', value: 'tf' },
  { key: 'ga', text: 'Gabon', flag: 'ga', value: 'ga' },
  { key: 'gm', text: 'Gambia', flag: 'gm', value: 'gm' },
  { key: 'ge', text: 'Georgia', flag: 'ge', value: 'ge' },
  { key: 'gh', text: 'Ghana', flag: 'gh', value: 'gh' },
  { key: 'gi', text: 'Gibraltar', flag: 'gi', value: 'gi' },
  { key: 'gr', text: 'Greece', flag: 'gr', value: 'gr' },
  { key: 'gl', text: 'Greenland', flag: 'gl', value: 'gl' },
  { key: 'gd', text: 'Grenada', flag: 'gd', value: 'gd' },
  { key: 'gp', text: 'Guadeloupe', flag: 'gp', value: 'gp' },
  { key: 'gu', text: 'Guam', flag: 'gu', value: 'gu' },
  { key: 'gt', text: 'Guatemala', flag: 'gt', value: 'gt' },
  { key: 'gn', text: 'Guinea', flag: 'gn', value: 'gn' },
  { key: 'gw', text: 'Guinea-Bissau', flag: 'gw', value: 'gw' },
  { key: 'gy', text: 'Guyana', flag: 'gy', value: 'gy' },
  { key: 'ht', text: 'Haiti', flag: 'ht', value: 'ht' },
  { key: 'hm', text: 'Heard Island', flag: 'hm', value: 'hm' },
  { key: 'hn', text: 'Honduras', flag: 'hn', value: 'hn' },
  { key: 'hk', text: 'Hong Kong', flag: 'hk', value: 'hk' },
  { key: 'hu', text: 'Hungary', flag: 'hu', value: 'hu' },
  { key: 'is', text: 'Iceland', flag: 'is', value: 'is' },
  { key: 'in', text: 'India', flag: 'in', value: 'in' },
  { key: 'id', text: 'Indonesia', flag: 'id', value: 'id' },
  { key: 'ir', text: 'Iran', flag: 'ir', value: 'ir' },
  { key: 'iq', text: 'Iraq', flag: 'iq', value: 'iq' },
  { key: 'ie', text: 'Ireland', flag: 'ie', value: 'ie' },
  { key: 'il', text: 'Israel', flag: 'il', value: 'il' },
  { key: 'jm', text: 'Jamaica', flag: 'jm', value: 'jm' },
  { key: 'sj', text: 'Svalbard/Jan Mayen', flag: 'sj', value: 'sj' },
  { key: 'jp', text: 'Japan', flag: 'jp', value: 'jp' },
  { key: 'jo', text: 'Jordan', flag: 'jo', value: 'jo' },
  { key: 'kz', text: 'Kazakhstan', flag: 'kz', value: 'kz' },
  { key: 'ke', text: 'Kenya', flag: 'ke', value: 'ke' },
  { key: 'ki', text: 'Kiribati', flag: 'ki', value: 'ki' },
  { key: 'kw', text: 'Kuwait', flag: 'kw', value: 'kw' },
  { key: 'kg', text: 'Kyrgyzstan', flag: 'kg', value: 'kg' },
  { key: 'la', text: 'Laos', flag: 'la', value: 'la' },
  { key: 'lv', text: 'Latvia', flag: 'lv', value: 'lv' },
  { key: 'lb', text: 'Lebanon', flag: 'lb', value: 'lb' },
  { key: 'ls', text: 'Lesotho', flag: 'ls', value: 'ls' },
  { key: 'lr', text: 'Liberia', flag: 'lr', value: 'lr' },
  { key: 'ly', text: 'Libya', flag: 'ly', value: 'ly' },
  { key: 'li', text: 'Liechtenstein', flag: 'li', value: 'li' },
  { key: 'lt', text: 'Lithuania', flag: 'lt', value: 'lt' },
  { key: 'lu', text: 'Luxembourg', flag: 'lu', value: 'lu' },
  { key: 'mo', text: 'Macau', flag: 'mo', value: 'mo' },
  { key: 'mk', text: 'Macedonia', flag: 'mk', value: 'mk' },
  { key: 'mg', text: 'Madagascar', flag: 'mg', value: 'mg' },
  { key: 'mw', text: 'Malawi', flag: 'mw', value: 'mw' },
  { key: 'my', text: 'Malaysia', flag: 'my', value: 'my' },
  { key: 'mv', text: 'Maldives', flag: 'mv', value: 'mv' },
  { key: 'ml', text: 'Mali', flag: 'ml', value: 'ml' },
  { key: 'mt', text: 'Malta', flag: 'mt', value: 'mt' },
  { key: 'mh', text: 'Marshall Islands', flag: 'mh', value: 'mh' },
  { key: 'mq', text: 'Martinique', flag: 'mq', value: 'mq' },
  { key: 'mr', text: 'Mauritania', flag: 'mr', value: 'mr' },
  { key: 'mu', text: 'Mauritius', flag: 'mu', value: 'mu' },
  { key: 'yt', text: 'Mayotte', flag: 'yt', value: 'yt' },
  { key: 'mx', text: 'Mexico', flag: 'mx', value: 'mx' },
  { key: 'fm', text: 'Micronesia', flag: 'fm', value: 'fm' },
  { key: 'md', text: 'Moldova', flag: 'md', value: 'md' },
  { key: 'mc', text: 'Monaco', flag: 'mc', value: 'mc' },
  { key: 'mn', text: 'Mongolia', flag: 'mn', value: 'mn' },
  { key: 'me', text: 'Montenegro', flag: 'me', value: 'me' },
  { key: 'ms', text: 'Montserrat', flag: 'ms', value: 'ms' },
  { key: 'ma', text: 'Morocco', flag: 'ma', value: 'ma' },
  { key: 'mz', text: 'Mozambique', flag: 'mz', value: 'mz' },
  { key: 'na', text: 'Namibia', flag: 'na', value: 'na' },
  { key: 'nr', text: 'Nauru', flag: 'nr', value: 'nr' },
  { key: 'np', text: 'Nepal', flag: 'np', value: 'np' },
  { key: 'an', text: 'Netherlandsantilles', flag: 'an', value: 'an' },
  { key: 'nc', text: 'New Caledonia', flag: 'nc', value: 'nc' },
  { key: 'pg', text: 'New Guinea', flag: 'pg', value: 'pg' },
  { key: 'nz', text: 'New Zealand', flag: 'nz', value: 'nz' },
  { key: 'ni', text: 'Nicaragua', flag: 'ni', value: 'ni' },
  { key: 'ne', text: 'Niger', flag: 'ne', value: 'ne' },
  { key: 'ng', text: 'Nigeria', flag: 'ng', value: 'ng' },
  { key: 'nu', text: 'Niue', flag: 'nu', value: 'nu' },
  { key: 'nf', text: 'Norfolk Island', flag: 'nf', value: 'nf' },
  { key: 'kp', text: 'North Korea', flag: 'kp', value: 'kp' },
  { key: 'mp', text: 'Northern Mariana Islands', flag: 'mp', value: 'mp' },
  { key: 'no', text: 'Norway', flag: 'no', value: 'no' },
  { key: 'om', text: 'Oman', flag: 'om', value: 'om' },
  { key: 'pk', text: 'Pakistan', flag: 'pk', value: 'pk' },
  { key: 'pw', text: 'Palau', flag: 'pw', value: 'pw' },
  { key: 'ps', text: 'Palestine', flag: 'ps', value: 'ps' },
  { key: 'pa', text: 'Panama', flag: 'pa', value: 'pa' },
  { key: 'py', text: 'Paraguay', flag: 'py', value: 'py' },
  { key: 'pe', text: 'Peru', flag: 'pe', value: 'pe' },
  { key: 'ph', text: 'Philippines', flag: 'ph', value: 'ph' },
  { key: 'pn', text: 'Pitcairn Islands', flag: 'pn', value: 'pn' },
  { key: 'pl', text: 'Poland', flag: 'pl', value: 'pl' },
  { key: 'pt', text: 'Portugal', flag: 'pt', value: 'pt' },
  { key: 'pr', text: 'Puerto Rico', flag: 'pr', value: 'pr' },
  { key: 'qa', text: 'Qatar', flag: 'qa', value: 'qa' },
  { key: 're', text: 'Reunion', flag: 're', value: 're' },
  { key: 'ro', text: 'Romania', flag: 'ro', value: 'ro' },
  { key: 'ru', text: 'Russia', flag: 'ru', value: 'ru' },
  { key: 'rw', text: 'Rwanda', flag: 'rw', value: 'rw' },
  { key: 'sh', text: 'Saint Helena', flag: 'sh', value: 'sh' },
  { key: 'kn', text: 'Saint Kitts and Nevis', flag: 'kn', value: 'kn' },
  { key: 'lc', text: 'Saint Lucia', flag: 'lc', value: 'lc' },
  { key: 'pm', text: 'Saint Pierre', flag: 'pm', value: 'pm' },
  { key: 'vc', text: 'Saint Vincent', flag: 'vc', value: 'vc' },
  { key: 'ws', text: 'Samoa', flag: 'ws', value: 'ws' },
  { key: 'sm', text: 'San Marino', flag: 'sm', value: 'sm' },
  { key: 'gs', text: 'Sandwich Islands', flag: 'gs', value: 'gs' },
  { key: 'st', text: 'Sao Tome', flag: 'st', value: 'st' },
  { key: 'sa', text: 'Saudi Arabia', flag: 'sa', value: 'sa' },
  { key: 'sn', text: 'Senegal', flag: 'sn', value: 'sn' },
  { key: 'cs', text: 'Serbia', flag: 'cs', value: 'cs' },
  { key: 'rs', text: 'Serbia', flag: 'rs', value: 'rs' },
  { key: 'sc', text: 'Seychelles', flag: 'sc', value: 'sc' },
  { key: 'sl', text: 'Sierra Leone', flag: 'sl', value: 'sl' },
  { key: 'sg', text: 'Singapore', flag: 'sg', value: 'sg' },
  { key: 'sk', text: 'Slovakia', flag: 'sk', value: 'sk' },
  { key: 'si', text: 'Slovenia', flag: 'si', value: 'si' },
  { key: 'sb', text: 'Solomon Islands', flag: 'sb', value: 'sb' },
  { key: 'so', text: 'Somalia', flag: 'so', value: 'so' },
  { key: 'za', text: 'South Africa', flag: 'za', value: 'za' },
  { key: 'kr', text: 'South Korea', flag: 'kr', value: 'kr' },
  { key: 'lk', text: 'Sri Lanka', flag: 'lk', value: 'lk' },
  { key: 'sd', text: 'Sudan', flag: 'sd', value: 'sd' },
  { key: 'sr', text: 'Suriname', flag: 'sr', value: 'sr' },
  { key: 'sz', text: 'Swaziland', flag: 'sz', value: 'sz' },
  { key: 'sy', text: 'Syria', flag: 'sy', value: 'sy' },
  { key: 'tw', text: 'Taiwan', flag: 'tw', value: 'tw' },
  { key: 'tj', text: 'Tajikistan', flag: 'tj', value: 'tj' },
  { key: 'tz', text: 'Tanzania', flag: 'tz', value: 'tz' },
  { key: 'th', text: 'Thailand', flag: 'th', value: 'th' },
  { key: 'tl', text: 'Timorleste', flag: 'tl', value: 'tl' },
  { key: 'tg', text: 'Togo', flag: 'tg', value: 'tg' },
  { key: 'tk', text: 'Tokelau', flag: 'tk', value: 'tk' },
  { key: 'to', text: 'Tonga', flag: 'to', value: 'to' },
  { key: 'tt', text: 'Trinidad', flag: 'tt', value: 'tt' },
  { key: 'tn', text: 'Tunisia', flag: 'tn', value: 'tn' },
  { key: 'tr', text: 'Turkey', flag: 'tr', value: 'tr' },
  { key: 'tm', text: 'Turkmenistan', flag: 'tm', value: 'tm' },
  { key: 'tv', text: 'Tuvalu', flag: 'tv', value: 'tv' },
  { key: 'ae', text: 'U.A.E.', flag: 'ae', value: 'ae' },
  { key: 'ug', text: 'Uganda', flag: 'ug', value: 'ug' },
  { key: 'ua', text: 'Ukraine', flag: 'ua', value: 'ua' },
  { key: 'gb', text: 'United Kingdom', flag: 'gb', value: 'gb' },
  { key: 'us', text: 'United States', flag: 'us', value: 'us' },
  { key: 'uy', text: 'Uruguay', flag: 'uy', value: 'uy' },
  { key: 'um', text: 'US Minor Islands', flag: 'um', value: 'um' },
  { key: 'vi', text: 'US Virgin Islands', flag: 'vi', value: 'vi' },
  { key: 'uz', text: 'Uzbekistan', flag: 'uz', value: 'uz' },
  { key: 'vu', text: 'Vanuatu', flag: 'vu', value: 'vu' },
  { key: 'va', text: 'Vatican City', flag: 'va', value: 'va' },
  { key: 've', text: 'Venezuela', flag: 've', value: 've' },
  { key: 'vn', text: 'Vietnam', flag: 'vn', value: 'vn' },
  { key: 'wf', text: 'Wallis and Futuna', flag: 'wf', value: 'wf' },
  { key: 'eh', text: 'Western Sahara', flag: 'eh', value: 'eh' },
  { key: 'ye', text: 'Yemen', flag: 'ye', value: 'ye' },
  { key: 'zm', text: 'Zambia', flag: 'zm', value: 'zm' },
  { key: 'zw', text: 'Zimbabwe', flag: 'zw', value: 'zw' },
];

export const COUNTRIES = [
  { key: 'af', text: 'Afghanistan', flag: 'af', value: 'af' },
  { key: 'ax', text: 'Aland Islands', flag: 'ax', value: 'ax' },
  { key: 'al', text: 'Albania', flag: 'al', value: 'al' },
  { key: 'dz', text: 'Algeria', flag: 'dz', value: 'dz' },
  { key: 'as', text: 'American Samoa', flag: 'as', value: 'as' },
  { key: 'ad', text: 'Andorra', flag: 'ad', value: 'ad' },
  { key: 'ao', text: 'Angola', flag: 'ao', value: 'ao' },
  { key: 'ai', text: 'Anguilla', flag: 'ai', value: 'ai' },
  { key: 'ag', text: 'Antigua', flag: 'ag', value: 'ag' },
  { key: 'ar', text: 'Argentina', flag: 'ar', value: 'ar' },
  { key: 'am', text: 'Armenia', flag: 'am', value: 'am' },
  { key: 'aw', text: 'Aruba', flag: 'aw', value: 'aw' },
  { key: 'au', text: 'Australia', flag: 'au', value: 'au' },
  { key: 'at', text: 'Austria', flag: 'at', value: 'at' },
  { key: 'az', text: 'Azerbaijan', flag: 'az', value: 'az' },
  { key: 'bs', text: 'Bahamas', flag: 'bs', value: 'bs' },
  { key: 'bh', text: 'Bahrain', flag: 'bh', value: 'bh' },
  { key: 'bd', text: 'Bangladesh', flag: 'bd', value: 'bd' },
  { key: 'bb', text: 'Barbados', flag: 'bb', value: 'bb' },
  { key: 'by', text: 'Belarus', flag: 'by', value: 'by' },
  { key: 'be', text: 'Belgium', flag: 'be', value: 'be' },
  { key: 'bz', text: 'Belize', flag: 'bz', value: 'bz' },
  { key: 'bj', text: 'Benin', flag: 'bj', value: 'bj' },
  { key: 'bm', text: 'Bermuda', flag: 'bm', value: 'bm' },
  { key: 'bt', text: 'Bhutan', flag: 'bt', value: 'bt' },
  { key: 'bo', text: 'Bolivia', flag: 'bo', value: 'bo' },
  { key: 'ba', text: 'Bosnia', flag: 'ba', value: 'ba' },
  { key: 'bw', text: 'Botswana', flag: 'bw', value: 'bw' },
  { key: 'bv', text: 'Bouvet Island', flag: 'bv', value: 'bv' },
  { key: 'br', text: 'Brazil', flag: 'br', value: 'br' },
  { key: 'vg', text: 'British Virgin Islands', flag: 'vg', value: 'vg' },
  { key: 'bn', text: 'Brunei', flag: 'bn', value: 'bn' },
  { key: 'bg', text: 'Bulgaria', flag: 'bg', value: 'bg' },
  { key: 'bf', text: 'Burkina Faso', flag: 'bf', value: 'bf' },
  { key: 'mm', text: 'Myanmar/Burma', flag: 'mm', value: 'mm' },
  { key: 'bi', text: 'Burundi', flag: 'bi', value: 'bi' },
  { key: 'tc', text: 'Caicos Islands', flag: 'tc', value: 'tc' },
  { key: 'kh', text: 'Cambodia', flag: 'kh', value: 'kh' },
  { key: 'cm', text: 'Cameroon', flag: 'cm', value: 'cm' },
  { key: 'ca', text: 'Canada', flag: 'ca', value: 'ca' },
  { key: 'cv', text: 'Cape Verde', flag: 'cv', value: 'cv' },
  { key: 'ky', text: 'Cayman Islands', flag: 'ky', value: 'ky' },
  { key: 'cf', text: 'Central African Republic', flag: 'cf', value: 'cf' },
  { key: 'td', text: 'Chad', flag: 'td', value: 'td' },
  { key: 'cl', text: 'Chile', flag: 'cl', value: 'cl' },
  { key: 'cn', text: 'China', flag: 'cn', value: 'cn' },
  { key: 'cx', text: 'Christmas Island', flag: 'cx', value: 'cx' },
  { key: 'cc', text: 'Cocos Islands', flag: 'cc', value: 'cc' },
  { key: 'co', text: 'Colombia', flag: 'co', value: 'co' },
  { key: 'km', text: 'Comoros', flag: 'km', value: 'km' },
  { key: 'cd', text: 'Congo', flag: 'cd', value: 'cd' },
  { key: 'cg', text: 'Congo Brazzaville', flag: 'cg', value: 'cg' },
  { key: 'ck', text: 'Cook Islands', flag: 'ck', value: 'ck' },
  { key: 'cr', text: 'Costa Rica', flag: 'cr', value: 'cr' },
  { key: 'ci', text: 'Cote Divoire', flag: 'ci', value: 'ci' },
  { key: 'hr', text: 'Croatia', flag: 'hr', value: 'hr' },
  { key: 'cu', text: 'Cuba', flag: 'cu', value: 'cu' },
  { key: 'cy', text: 'Cyprus', flag: 'cy', value: 'cy' },
  { key: 'cz', text: 'Czech Republic', flag: 'cz', value: 'cz' },
  { key: 'dk', text: 'Denmark', flag: 'dk', value: 'dk' },
  { key: 'dj', text: 'Djibouti', flag: 'dj', value: 'dj' },
  { key: 'dm', text: 'Dominica', flag: 'dm', value: 'dm' },
  { key: 'do', text: 'Dominican Republic', flag: 'do', value: 'do' },
  { key: 'ec', text: 'Ecuador', flag: 'ec', value: 'ec' },
  { key: 'eg', text: 'Egypt', flag: 'eg', value: 'eg' },
  { key: 'sv', text: 'El Salvador', flag: 'sv', value: 'sv' },
  { key: 'gq', text: 'Equatorial Guinea', flag: 'gq', value: 'gq' },
  { key: 'er', text: 'Eritrea', flag: 'er', value: 'er' },
  { key: 'ee', text: 'Estonia', flag: 'ee', value: 'ee' },
  { key: 'et', text: 'Ethiopia', flag: 'et', value: 'et' },
  { key: 'eu', text: 'Europeanunion', flag: 'eu', value: 'eu' },
  { key: 'fk', text: 'Falkland Islands', flag: 'fk', value: 'fk' },
  { key: 'fo', text: 'Faroe Islands', flag: 'fo', value: 'fo' },
  { key: 'fj', text: 'Fiji', flag: 'fj', value: 'fj' },
  { key: 'fi', text: 'Finland', flag: 'fi', value: 'fi' },
  { key: 'fr', text: 'France', flag: 'fr', value: 'fr' },
  { key: 'gf', text: 'French Guiana', flag: 'gf', value: 'gf' },
  { key: 'pf', text: 'French Polynesia', flag: 'pf', value: 'pf' },
  { key: 'tf', text: 'French Territories', flag: 'tf', value: 'tf' },
  { key: 'ga', text: 'Gabon', flag: 'ga', value: 'ga' },
  { key: 'gm', text: 'Gambia', flag: 'gm', value: 'gm' },
  { key: 'ge', text: 'Georgia', flag: 'ge', value: 'ge' },
  { key: 'de', text: 'Germany', flag: 'de', value: 'de' },
  { key: 'gh', text: 'Ghana', flag: 'gh', value: 'gh' },
  { key: 'gi', text: 'Gibraltar', flag: 'gi', value: 'gi' },
  { key: 'gr', text: 'Greece', flag: 'gr', value: 'gr' },
  { key: 'gl', text: 'Greenland', flag: 'gl', value: 'gl' },
  { key: 'gd', text: 'Grenada', flag: 'gd', value: 'gd' },
  { key: 'gp', text: 'Guadeloupe', flag: 'gp', value: 'gp' },
  { key: 'gu', text: 'Guam', flag: 'gu', value: 'gu' },
  { key: 'gt', text: 'Guatemala', flag: 'gt', value: 'gt' },
  { key: 'gn', text: 'Guinea', flag: 'gn', value: 'gn' },
  { key: 'gw', text: 'Guinea-Bissau', flag: 'gw', value: 'gw' },
  { key: 'gy', text: 'Guyana', flag: 'gy', value: 'gy' },
  { key: 'ht', text: 'Haiti', flag: 'ht', value: 'ht' },
  { key: 'hm', text: 'Heard Island', flag: 'hm', value: 'hm' },
  { key: 'hn', text: 'Honduras', flag: 'hn', value: 'hn' },
  { key: 'hk', text: 'Hong Kong', flag: 'hk', value: 'hk' },
  { key: 'hu', text: 'Hungary', flag: 'hu', value: 'hu' },
  { key: 'is', text: 'Iceland', flag: 'is', value: 'is' },
  { key: 'in', text: 'India', flag: 'in', value: 'in' },
  { key: 'id', text: 'Indonesia', flag: 'id', value: 'id' },
  { key: 'ir', text: 'Iran', flag: 'ir', value: 'ir' },
  { key: 'iq', text: 'Iraq', flag: 'iq', value: 'iq' },
  { key: 'ie', text: 'Ireland', flag: 'ie', value: 'ie' },
  { key: 'il', text: 'Israel', flag: 'il', value: 'il' },
  { key: 'it', text: 'Italy', flag: 'it', value: 'it' },
  { key: 'jm', text: 'Jamaica', flag: 'jm', value: 'jm' },
  { key: 'sj', text: 'Svalbard/Jan Mayen', flag: 'sj', value: 'sj' },
  { key: 'jp', text: 'Japan', flag: 'jp', value: 'jp' },
  { key: 'jo', text: 'Jordan', flag: 'jo', value: 'jo' },
  { key: 'kz', text: 'Kazakhstan', flag: 'kz', value: 'kz' },
  { key: 'ke', text: 'Kenya', flag: 'ke', value: 'ke' },
  { key: 'ki', text: 'Kiribati', flag: 'ki', value: 'ki' },
  { key: 'kw', text: 'Kuwait', flag: 'kw', value: 'kw' },
  { key: 'kg', text: 'Kyrgyzstan', flag: 'kg', value: 'kg' },
  { key: 'la', text: 'Laos', flag: 'la', value: 'la' },
  { key: 'lv', text: 'Latvia', flag: 'lv', value: 'lv' },
  { key: 'lb', text: 'Lebanon', flag: 'lb', value: 'lb' },
  { key: 'ls', text: 'Lesotho', flag: 'ls', value: 'ls' },
  { key: 'lr', text: 'Liberia', flag: 'lr', value: 'lr' },
  { key: 'ly', text: 'Libya', flag: 'ly', value: 'ly' },
  { key: 'li', text: 'Liechtenstein', flag: 'li', value: 'li' },
  { key: 'lt', text: 'Lithuania', flag: 'lt', value: 'lt' },
  { key: 'lu', text: 'Luxembourg', flag: 'lu', value: 'lu' },
  { key: 'mo', text: 'Macau', flag: 'mo', value: 'mo' },
  { key: 'mk', text: 'Macedonia', flag: 'mk', value: 'mk' },
  { key: 'mg', text: 'Madagascar', flag: 'mg', value: 'mg' },
  { key: 'mw', text: 'Malawi', flag: 'mw', value: 'mw' },
  { key: 'my', text: 'Malaysia', flag: 'my', value: 'my' },
  { key: 'mv', text: 'Maldives', flag: 'mv', value: 'mv' },
  { key: 'ml', text: 'Mali', flag: 'ml', value: 'ml' },
  { key: 'mt', text: 'Malta', flag: 'mt', value: 'mt' },
  { key: 'mh', text: 'Marshall Islands', flag: 'mh', value: 'mh' },
  { key: 'mq', text: 'Martinique', flag: 'mq', value: 'mq' },
  { key: 'mr', text: 'Mauritania', flag: 'mr', value: 'mr' },
  { key: 'mu', text: 'Mauritius', flag: 'mu', value: 'mu' },
  { key: 'yt', text: 'Mayotte', flag: 'yt', value: 'yt' },
  { key: 'mx', text: 'Mexico', flag: 'mx', value: 'mx' },
  { key: 'fm', text: 'Micronesia', flag: 'fm', value: 'fm' },
  { key: 'md', text: 'Moldova', flag: 'md', value: 'md' },
  { key: 'mc', text: 'Monaco', flag: 'mc', value: 'mc' },
  { key: 'mn', text: 'Mongolia', flag: 'mn', value: 'mn' },
  { key: 'me', text: 'Montenegro', flag: 'me', value: 'me' },
  { key: 'ms', text: 'Montserrat', flag: 'ms', value: 'ms' },
  { key: 'ma', text: 'Morocco', flag: 'ma', value: 'ma' },
  { key: 'mz', text: 'Mozambique', flag: 'mz', value: 'mz' },
  { key: 'na', text: 'Namibia', flag: 'na', value: 'na' },
  { key: 'nr', text: 'Nauru', flag: 'nr', value: 'nr' },
  { key: 'np', text: 'Nepal', flag: 'np', value: 'np' },
  { key: 'nl', text: 'Netherlands', flag: 'nl', value: 'nl' },
  { key: 'an', text: 'Netherlandsantilles', flag: 'an', value: 'an' },
  { key: 'nc', text: 'New Caledonia', flag: 'nc', value: 'nc' },
  { key: 'pg', text: 'New Guinea', flag: 'pg', value: 'pg' },
  { key: 'nz', text: 'New Zealand', flag: 'nz', value: 'nz' },
  { key: 'ni', text: 'Nicaragua', flag: 'ni', value: 'ni' },
  { key: 'ne', text: 'Niger', flag: 'ne', value: 'ne' },
  { key: 'ng', text: 'Nigeria', flag: 'ng', value: 'ng' },
  { key: 'nu', text: 'Niue', flag: 'nu', value: 'nu' },
  { key: 'nf', text: 'Norfolk Island', flag: 'nf', value: 'nf' },
  { key: 'kp', text: 'North Korea', flag: 'kp', value: 'kp' },
  { key: 'mp', text: 'Northern Mariana Islands', flag: 'mp', value: 'mp' },
  { key: 'no', text: 'Norway', flag: 'no', value: 'no' },
  { key: 'om', text: 'Oman', flag: 'om', value: 'om' },
  { key: 'pk', text: 'Pakistan', flag: 'pk', value: 'pk' },
  { key: 'pw', text: 'Palau', flag: 'pw', value: 'pw' },
  { key: 'ps', text: 'Palestine', flag: 'ps', value: 'ps' },
  { key: 'pa', text: 'Panama', flag: 'pa', value: 'pa' },
  { key: 'py', text: 'Paraguay', flag: 'py', value: 'py' },
  { key: 'pe', text: 'Peru', flag: 'pe', value: 'pe' },
  { key: 'ph', text: 'Philippines', flag: 'ph', value: 'ph' },
  { key: 'pn', text: 'Pitcairn Islands', flag: 'pn', value: 'pn' },
  { key: 'pl', text: 'Poland', flag: 'pl', value: 'pl' },
  { key: 'pt', text: 'Portugal', flag: 'pt', value: 'pt' },
  { key: 'pr', text: 'Puerto Rico', flag: 'pr', value: 'pr' },
  { key: 'qa', text: 'Qatar', flag: 'qa', value: 'qa' },
  { key: 're', text: 'Reunion', flag: 're', value: 're' },
  { key: 'ro', text: 'Romania', flag: 'ro', value: 'ro' },
  { key: 'ru', text: 'Russia', flag: 'ru', value: 'ru' },
  { key: 'rw', text: 'Rwanda', flag: 'rw', value: 'rw' },
  { key: 'sh', text: 'Saint Helena', flag: 'sh', value: 'sh' },
  { key: 'kn', text: 'Saint Kitts and Nevis', flag: 'kn', value: 'kn' },
  { key: 'lc', text: 'Saint Lucia', flag: 'lc', value: 'lc' },
  { key: 'pm', text: 'Saint Pierre', flag: 'pm', value: 'pm' },
  { key: 'vc', text: 'Saint Vincent', flag: 'vc', value: 'vc' },
  { key: 'ws', text: 'Samoa', flag: 'ws', value: 'ws' },
  { key: 'sm', text: 'San Marino', flag: 'sm', value: 'sm' },
  { key: 'gs', text: 'Sandwich Islands', flag: 'gs', value: 'gs' },
  { key: 'st', text: 'Sao Tome', flag: 'st', value: 'st' },
  { key: 'sa', text: 'Saudi Arabia', flag: 'sa', value: 'sa' },
  { key: 'sn', text: 'Senegal', flag: 'sn', value: 'sn' },
  { key: 'cs', text: 'Serbia', flag: 'cs', value: 'cs' },
  { key: 'rs', text: 'Serbia', flag: 'rs', value: 'rs' },
  { key: 'sc', text: 'Seychelles', flag: 'sc', value: 'sc' },
  { key: 'sl', text: 'Sierra Leone', flag: 'sl', value: 'sl' },
  { key: 'sg', text: 'Singapore', flag: 'sg', value: 'sg' },
  { key: 'sk', text: 'Slovakia', flag: 'sk', value: 'sk' },
  { key: 'si', text: 'Slovenia', flag: 'si', value: 'si' },
  { key: 'sb', text: 'Solomon Islands', flag: 'sb', value: 'sb' },
  { key: 'so', text: 'Somalia', flag: 'so', value: 'so' },
  { key: 'za', text: 'South Africa', flag: 'za', value: 'za' },
  { key: 'kr', text: 'South Korea', flag: 'kr', value: 'kr' },
  { key: 'es', text: 'Spain', flag: 'es', value: 'es' },
  { key: 'lk', text: 'Sri Lanka', flag: 'lk', value: 'lk' },
  { key: 'sd', text: 'Sudan', flag: 'sd', value: 'sd' },
  { key: 'sr', text: 'Suriname', flag: 'sr', value: 'sr' },
  { key: 'sz', text: 'Swaziland', flag: 'sz', value: 'sz' },
  { key: 'se', text: 'Sweden', flag: 'se', value: 'se' },
  { key: 'ch', text: 'Switzerland', flag: 'ch', value: 'ch' },
  { key: 'sy', text: 'Syria', flag: 'sy', value: 'sy' },
  { key: 'tw', text: 'Taiwan', flag: 'tw', value: 'tw' },
  { key: 'tj', text: 'Tajikistan', flag: 'tj', value: 'tj' },
  { key: 'tz', text: 'Tanzania', flag: 'tz', value: 'tz' },
  { key: 'th', text: 'Thailand', flag: 'th', value: 'th' },
  { key: 'tl', text: 'Timorleste', flag: 'tl', value: 'tl' },
  { key: 'tg', text: 'Togo', flag: 'tg', value: 'tg' },
  { key: 'tk', text: 'Tokelau', flag: 'tk', value: 'tk' },
  { key: 'to', text: 'Tonga', flag: 'to', value: 'to' },
  { key: 'tt', text: 'Trinidad', flag: 'tt', value: 'tt' },
  { key: 'tn', text: 'Tunisia', flag: 'tn', value: 'tn' },
  { key: 'tr', text: 'Turkey', flag: 'tr', value: 'tr' },
  { key: 'tm', text: 'Turkmenistan', flag: 'tm', value: 'tm' },
  { key: 'tv', text: 'Tuvalu', flag: 'tv', value: 'tv' },
  { key: 'ae', text: 'U.A.E.', flag: 'ae', value: 'ae' },
  { key: 'ug', text: 'Uganda', flag: 'ug', value: 'ug' },
  { key: 'ua', text: 'Ukraine', flag: 'ua', value: 'ua' },
  { key: 'gb', text: 'United Kingdom', flag: 'gb', value: 'gb' },
  { key: 'us', text: 'United States', flag: 'us', value: 'us' },
  { key: 'uy', text: 'Uruguay', flag: 'uy', value: 'uy' },
  { key: 'um', text: 'US Minor Islands', flag: 'um', value: 'um' },
  { key: 'vi', text: 'US Virgin Islands', flag: 'vi', value: 'vi' },
  { key: 'uz', text: 'Uzbekistan', flag: 'uz', value: 'uz' },
  { key: 'vu', text: 'Vanuatu', flag: 'vu', value: 'vu' },
  { key: 'va', text: 'Vatican City', flag: 'va', value: 'va' },
  { key: 've', text: 'Venezuela', flag: 've', value: 've' },
  { key: 'vn', text: 'Vietnam', flag: 'vn', value: 'vn' },
  { key: 'wf', text: 'Wallis and Futuna', flag: 'wf', value: 'wf' },
  { key: 'eh', text: 'Western Sahara', flag: 'eh', value: 'eh' },
  { key: 'ye', text: 'Yemen', flag: 'ye', value: 'ye' },
  { key: 'zm', text: 'Zambia', flag: 'zm', value: 'zm' },
  { key: 'zw', text: 'Zimbabwe', flag: 'zw', value: 'zw' },
];
